Policies:
- Statement:
  - Action:
    - ec2:DeleteSecurityGroup
    - ec2:DescribeSecurityGroups
    - ec2:RevokeSecurityGroupEgress
    - ec2:RevokeSecurityGroupIngress
    - logs:PutMetricFilter
    - logs:CreateLogGroup
    - sns:Publish
    - sns:CreateTopic
    - sns:Subscribe
    - sts:GetCallerIdentity
    - sts:AssumeRole
    Effect: Allow
    Resource: "*"
  Version: '2012-10-17'
