AWSTemplateFormatVersion: 2010-09-09
Description: Configure to enable use of your account as a target account for Remediation from lambdas in Master Account.

Parameters:
  MasterAccountId:
    Type: String
    Description: AWS Account Id of the Master account (the account in which Lambdas will be imported).
    MaxLength: 12
    MinLength: 12

Resources:
  QualysRemediationRole-Policy:
    Type: AWS::IAM::Policy
    PolicyName: "QualysRemediationRole-Policy"
    PolicyDocument:
      Version: "2012-10-17"
      Statement:
        -
          Action:
            - ec2:DeleteSecurityGroup
            - ec2:DescribeSecurityGroups
            - ec2:RevokeSecurityGroupEgress
            - ec2:RevokeSecurityGroupIngress
            - logs:PutMetricFilter
            - logs:CreateLogGroup
            - sns:Publish
            - sns:CreateTopic
            - sns:Subscribe
            - sts:GetCallerIdentity
            - sts:AssumeRole
          Effect: Allow
          Resource: "*"
     
  QualysRemediationRole:
    Type: AWS::IAM::Role
    DependsOn: !Ref QualysRemediationRole-Policy
    Properties:
      RoleName: QualysRemediationRole
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS:
                - !Ref MasterAccountId
            Action:
              - sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/QualysRemediationRole-Policy
